[build]
  command = "npx prisma generate && npx prisma db push --accept-data-loss && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_GENERATE_DATAPROXY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
